version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sds
      MONGO_INITDB_ROOT_PASSWORD: sds
      MONGO_INITDB_DATABASE: mysds
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    restart: always

  keycloak:
    image: "quay.io/keycloak/keycloak:23.0.6"
    container_name: quarkus-keycloak
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./conf/keycloak:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    restart: always