version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sds
      MONGO_INITDB_ROOT_PASSWORD: sds
      MONGO_INITDB_DATABASE: mysds
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    restart: always

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: scala_app
#    ports:
#      - "9000:9000"
#    environment:
#      MONGO_URI: "mongodb://sds:sds@mongodb:27017/mysdsscala?authSource=admin"
#    depends_on:
#      - mongodb
#    restart: always